### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by jamesperi** [johnsonlee/virt#1]
Hey i'm seeing this error when I try to install via NPM (centos 7):

```
> virt@2.0.0 install /home/jamesperi/projects/restful-ucpe/node_modules/virt
> node-gyp rebuild

make: Entering directory `/home/jamesperi/projects/restful-ucpe/node_modules/virt/build'
  CXX(target) Release/obj.target/virt/src/connection.o
In file included from ../src/connection.cc:1:0:
../src/connection.h:5:29: fatal error: libvirt/libvirt.h: No such file or directory
 #include <libvirt/libvirt.h>
                             ^
compilation terminated.
```

Do you have any ideas what might be the issue?

**Comment by jamesperi** [comment]
looks like I needed libvirt_devel. that seemed to solve this one, but the next issue is 

```
make: Entering directory `/home/jamesperi/projects/restful-ucpe/node_modules/virt/build'
  CXX(target) Release/obj.target/virt/src/connection.o
In file included from ../src/connection.cc:1:0:
../src/connection.h:15:37: error: specialization of ‘Pointer<_virConnect*>’ after instantiation
     template <class F> friend class Pointer;
                                     ^
make: *** [Release/obj.target/virt/src/connection.o] Error 1
```

Another dependency I'm guessing. pointer.h exists .. 

Any way you may be able to document the dependencies necessary to compile this one?

**Comment by johnsonlee** [comment]
The `pointer.h` is a part of source code, I think this issue might caused by the libvirt.

Can you provide the following informations:
- OS
- libvirt version
- Node version

The virt module only support node.js 0.10.x and higher

**Comment by ChrisM2** [comment]
I've got the same issue - running Debian 8.1 (jessie) installed this morning, libvirt-dev is 1.2.9-9, and node is build from source at v0.12.4.
I think it might be related to a breaking change in gcc ( http://stackoverflow.com/questions/21112148/specialization-of-member-function-template-after-instantiation-error-and-order ) - I'm using gcc 4:4.9.2-2 if it helps

**Comment by ChrisM2** [comment]
cheers - just confirmed it builds sucesfully now, thanks for a prompt fix
